create table if not exists public.requests (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  request_type text not null check (request_type in ('empresa', 'talento')),
  name text not null,
  email text not null,
  organization text not null,
  message text not null,
  status text not null default 'novo' check (status in ('novo', 'em_analise', 'contatado', 'arquivado')),
  is_test boolean not null default true
);

alter table public.requests enable row level security;

create policy "Permitir novos cadastros publicos"
on public.requests
for insert
to anon
with check (
  request_type in ('empresa', 'talento')
  and char_length(name) between 2 and 120
  and char_length(email) between 5 and 180
  and char_length(organization) between 2 and 180
  and char_length(message) between 5 and 3000
);

comment on table public.requests is 'Solicitacoes demonstrativas de empresas e talentos do Casting Attual 360.';
