-- Casting Attual 360 - fluxo administrativo de solicitacoes publicas
-- Idempotente e compatível com a tabela public.requests criada na migration 001.

alter table public.requests
  add column if not exists updated_at timestamptz not null default now(),
  add column if not exists assigned_to text not null default '',
  add column if not exists internal_notes text not null default '';

alter table public.requests
  drop constraint if exists requests_assigned_to_length,
  add constraint requests_assigned_to_length check (char_length(assigned_to) <= 120),
  drop constraint if exists requests_internal_notes_length,
  add constraint requests_internal_notes_length check (char_length(internal_notes) <= 2000);

create index if not exists requests_admin_queue_idx
  on public.requests (status, created_at desc);

create table if not exists public.request_history (
  id bigint generated by default as identity primary key,
  request_id bigint not null references public.requests(id) on delete cascade,
  changed_at timestamptz not null default now(),
  changed_by_email text,
  changes jsonb not null default '{}'::jsonb
);

create index if not exists request_history_request_idx
  on public.request_history (request_id, changed_at desc);

create or replace function public.set_request_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists requests_set_updated_at on public.requests;
create trigger requests_set_updated_at
before update on public.requests
for each row
execute function public.set_request_updated_at();

create or replace function public.log_request_admin_changes()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  delta jsonb := '{}'::jsonb;
  actor_email text;
begin
  if new.request_type is distinct from old.request_type then
    delta := delta || jsonb_build_object('request_type', jsonb_build_object('from', to_jsonb(old.request_type), 'to', to_jsonb(new.request_type)));
  end if;
  if new.name is distinct from old.name then
    delta := delta || jsonb_build_object('name', jsonb_build_object('from', to_jsonb(old.name), 'to', to_jsonb(new.name)));
  end if;
  if new.email is distinct from old.email then
    delta := delta || jsonb_build_object('email', jsonb_build_object('from', to_jsonb(old.email), 'to', to_jsonb(new.email)));
  end if;
  if new.organization is distinct from old.organization then
    delta := delta || jsonb_build_object('organization', jsonb_build_object('from', to_jsonb(old.organization), 'to', to_jsonb(new.organization)));
  end if;
  if new.status is distinct from old.status then
    delta := delta || jsonb_build_object('status', jsonb_build_object('from', to_jsonb(old.status), 'to', to_jsonb(new.status)));
  end if;
  if new.assigned_to is distinct from old.assigned_to then
    delta := delta || jsonb_build_object('assigned_to', jsonb_build_object('from', to_jsonb(old.assigned_to), 'to', to_jsonb(new.assigned_to)));
  end if;
  if new.internal_notes is distinct from old.internal_notes then
    delta := delta || jsonb_build_object('internal_notes', jsonb_build_object('from', to_jsonb(old.internal_notes), 'to', to_jsonb(new.internal_notes)));
  end if;

  if delta <> '{}'::jsonb then
    begin
      actor_email := auth.jwt() ->> 'email';
    exception when others then
      actor_email := null;
    end;

    insert into public.request_history (request_id, changed_by_email, changes)
    values (new.id, actor_email, delta);
  end if;

  return new;
end;
$$;

revoke all on function public.log_request_admin_changes() from public;

drop trigger if exists requests_log_admin_changes on public.requests;
create trigger requests_log_admin_changes
after update on public.requests
for each row
execute function public.log_request_admin_changes();

alter table public.request_history enable row level security;

revoke all on table public.request_history from anon;
revoke all on table public.request_history from authenticated;
grant select on table public.request_history to authenticated;

grant select, update on table public.requests to authenticated;

drop policy if exists "Administrador consulta solicitacoes" on public.requests;
create policy "Administrador consulta solicitacoes"
on public.requests
for select
to authenticated
using (
  exists (
    select 1
    from public.admin_users
    where admin_users.user_id = (select auth.uid())
  )
);

drop policy if exists "Administrador atualiza solicitacoes" on public.requests;
create policy "Administrador atualiza solicitacoes"
on public.requests
for update
to authenticated
using (
  exists (
    select 1
    from public.admin_users
    where admin_users.user_id = (select auth.uid())
  )
)
with check (
  exists (
    select 1
    from public.admin_users
    where admin_users.user_id = (select auth.uid())
  )
);

drop policy if exists "Administrador consulta historico de solicitacoes" on public.request_history;
create policy "Administrador consulta historico de solicitacoes"
on public.request_history
for select
to authenticated
using (
  exists (
    select 1
    from public.admin_users
    where admin_users.user_id = (select auth.uid())
  )
);

comment on table public.request_history is
  'Historico auditavel de alteracoes administrativas nas solicitacoes do Casting Attual 360.';
